### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by elpiel** [rzip/rzip#1]
We should setup a CI.

* Travis - really easy to setup but sometimes it takes a lot of time for a queued item to get running
* Azure
* CircleCi
* AppVeyor

**Comment by DavidBM** [comment]
I setup Bussy.works, but then I realized that there is no option to be open to everyone. Therefore better to just use CircleCI

**Comment by elpiel** [comment]
CircleCI requires quite some setup, but I think it will work as long a s we put some effort in it as well. Also a good start will be `cargo make` it will greatly improve the ease in which we build on CI.

**Comment by DavidBM** [comment]
I already added CircleCI. Basically, I copy pasted a version of the yml for keeping the cache between compilations.

We can change it later if you want, for now it is working.

**Comment by DavidBM** [comment]
I will close this one as the CI is already setup. We can change the script in #6
