### ISSUE TITLE
Clean up test directory even if tests fail

### ISSUE THREAD

**Issue by elpiel** [rzip/rzip#12]
The problem is that if a test panics, the directories/files that were created before that are left alone.

**Comment by DavidBM** [comment]
Maybe we can do it in a way that we create a new folder each time that is ensured to be deleted as first step. Kid of:

rm -rf test_sandbox
mkdir test_sandbox
... test running inside test_sandbox ...

**Comment by elpiel** [comment]
I tried remove_dir_all, but we need to skip the error if it's `Not found` kind, I just couldn't figure it out yesterday and though I might was well open an issue and discuss other options as well.
https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html

**Comment by DavidBM** [comment]
Well, if it is not found, then the folder doesn't exist, that is what we want. I think that is good.
Maybe I'm not understanding the issue

**Comment by elpiel** [comment]
If it doesn't exist it will Error, if it errors it quits the test, so we need to catch the `Not found` error and allow the test to continue.

**Comment by DavidBM** [comment]
Ok, I see. Then, we can build a helper function that should be called in each test. There is no beforeEach in rust, right?

**Comment by DavidBM** [comment]
Maybe this can help: https://medium.com/@ericdreichert/test-setup-and-teardown-in-rust-without-a-framework-ba32d97aa5ab

**Comment by DavidBM** [comment]
This #18 may close this one.

**Comment by DavidBM** [comment]
Closing as we can sort of guarantee with #18 .
