### ISSUE TITLE
Address CircleCi

### ISSUE THREAD

**Issue by elpiel** [rzip/rzip#13]
Things to work out:
- Rustup toolchain for ~nighlty~ stable
- Setup cargo make & rustfmt & clippy
- Cache

**Comment by DavidBM** [comment]
- Rustup toolchain for nighlty
  - Do yo mean to keep it as our normal CI? Wouldn't it be better to relay in stable? Or, can we have both?

**Comment by elpiel** [comment]
I tried remove_dir_all, but we need to skip the error if it's `Not found` kind, I just couldn't figure it out yesterday and though I might was well open an issue and discuss other options as well.
https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html

**Comment by DavidBM** [comment]
Is https://github.com/async-rs/async-std an option?

**Comment by DavidBM** [comment]
Just wondering. Would it be better to use GitHub actions instead of CircleCI?

I don't know what is better, as maybe having everything in github is not the best idea? But maybe we win something in integration compared with CircleCI?.

What do you think?

**Comment by elpiel** [comment]
For me the underlying build steps are a bit more important. If we can setup Circle CI faster to build our project and run all the checks we will have more time to develop instead of setting this up.

I personally haven't worked with GitHub actions, so I can't give a clear answer here.
I might focus on the build steps instead and you can decide what should we use for them?

**Comment by DavidBM** [comment]
If we don't know it, I think we may just stick to what we know. If at some point we get to know about github actions, we can decide.

**Comment by elpiel** [comment]
Ok, I am closing this issue then, since now we have a good start with CircleCI and the points were covered in #16
