### ISSUE TITLE
CLI options

### ISSUE THREAD

**Issue by elpiel** [rzip/rzip#3]
There are already some very good libraries that will help us do the requirements as long as they allows as they provide the necessary options required to implement all options of `unzip` 

- [clap](https://crates.io/crates/clap)
- ....

**Comment by DavidBM** [comment]
Ok with clap.

**Comment by elpiel** [comment]
With clap we need to check if we can do all the options as they are shown in `unzip` if we are going to do the same options and as close to `unzip` as possible for seamless migration to our tool for users.

**Comment by DavidBM** [comment]
I made a fast read and I didn't see anything to complex. I think it will be more internal logic and build the proper structs for representing the interactions between flags.

**Comment by elpiel** [comment]
Ok, we can try out `Clap` and try to replicate all the options at first and if something is not fitting we can always improvize.

**Comment by DavidBM** [comment]
I will close this as we already are using clap and for what I see it supports everything we need.
