### ISSUE TITLE
Consider Cargo-make

### ISSUE THREAD

**Issue by elpiel** [rzip/rzip#6]
I'm using [`cargo-make`](https://github.com/sagiegurari/cargo-make) in other projects and it's just like a Makefile, but with pre-defined tasks and the ability to add more or override existing ones.
It gives us also a flow for the CI #1 and adding those checks to make the build fail is also a good start for feedback before PR review.
As a bonus it will help other people to get started with our project if they want to contribute, 1 command to run the tests / rustfmt (formatting the code) & check for `clippy` warnings ( good practices ).

The pre-defined tasks can be found here [Makefile.stable.toml](https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml)

**Comment by DavidBM** [comment]
Yeah. I'm down for using cargo-make.
